plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.openapi.generator' version '7.25.0'
}

group = 'com.MarketOfferHub'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'

    implementation 'org.springframework.ai:spring-ai-starter-model-openai'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.1.0'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    runtimeOnly 'org.postgresql:postgresql'

    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'

    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

openApiGenerate {
    generatorName = 'spring'

    inputSpec = "$projectDir/src/main/resources/openapi.yml"

    outputDir = "$buildDir/generated"

    apiPackage = 'com.marketofferhub.api'
    modelPackage = 'com.marketofferhub.api.dto'

    configOptions = [
            useSpringBoot3        : 'true',
            interfaceOnly         : 'true',
            skipDefaultInterface  : 'true',
            useTags               : 'true',
            dateLibrary           : 'java8',
            serializationLibrary  : 'jackson',
            useBeanValidation     : 'true',
            hideGenerationTimestamp: 'true'
    ]

    globalProperties = [
            modelDocs: 'false',
            modelTests: 'false',
            apiDocs: 'false',
            apiTests: 'false'
    ]

}

sourceSets {
    main {
        java {
            srcDir "$buildDir/generated/src/main/java"
        }
    }
}

tasks.named('compileJava') {
    dependsOn tasks.named('openApiGenerate')
}

tasks.named('test') {
    useJUnitPlatform()
}
